## MySQL.
# default: &default
#   adapter: mysql2
#   encoding: unicode
#   pool: 5
#   host: localhost

## Postgres SQL.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: BlueBank

  ## MySQL.
  # username: root
  # password:

  ## Postgres SQL.
  username: postgres
  password: admin

production:
  <<: *default